# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Strange Phone
email: art@strangephone.com
phone: "+81 3 4589 4757"
description: > # this means to ignore newlines until "baseurl:"
  a simple, but strange, payphone
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strangephone.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: strangephone


# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

instagram_username: strange_phone 
instagram_user_id: 5631423697
instagram_client_id: 1b9ca331fe614565ba44d293d9b967ee
instagram_access_token:  5631423697.1677ed0.0ab6dab4dfd3488ca8d840740c268ff9
newone: 5631423697.1677ed0.0ab6dab4dfd3488ca8d840740c268ff9

exclude:    ['CNAME','Makefile','Gemfile','Gemfile.lock','galleries.html',Makefile','s3_website.yml','_config.example.yml','s3_website.example.yml','README.md','.gitignore', 'node_modules']
